### ISSUE TITLE
base64 complain when no arg

### ISSUE THREAD

**Issue by jerabaul29** [jerabaul29/qrdump#2]
Should rather display help instead. Reported by @gtheler . Will fix soon.

**Comment by jerabaul29** [comment]
Now displaying help (empty for now, so TODO):

```
$ qrdump
no argument, displaying help...
TODO help
```

I consider it fixed, writing the help is todo / undergoing.

**Comment by gtheler** [comment]
When I try to run the example I get

```
gtheler@tom:~/codigos/3ros/build/qrdump/src$ ./qrdump.sh --create-A4 --base64 --safe-mode --output ./pdf_dump.pdf --input dummy.dat
no argument, displaying help...
TODO help
gtheler@tom:~/codigos/3ros/build/qrdump/src$ 
```

but this issue has been already closed.

**Comment by jerabaul29** [comment]
Sorry, I had made a mistake when pushing, last push fixed this, confirm?

**Comment by gtheler** [comment]
it works now

**Comment by jerabaul29** [comment]
Perfect, thanks, closing :) .
