### ISSUE TITLE
absolute paths

### ISSUE THREAD

**Issue by jerabaul29** [jerabaul29/qrdump#3]
Script complains about absolute paths. Reported by @gtheler .

**Comment by jerabaul29** [comment]
Both absolute, relative, and home folder paths should work now @gtheler . Let me know and close if you have possibility to confirm :) .

**Comment by gtheler** [comment]
It works. Apparently I do not have enough permissions to close issues.

**Comment by jerabaul29** [comment]
Perfect, many thanks for the confirmation, closing.
