### ISSUE TITLE
No pdf output

### ISSUE THREAD

**Issue by jerabaul29** [jerabaul29/qrdump#4]
@gtheler reports no pdf output, probably missing package.

@gtheler , do you have any error message?

**Comment by jerabaul29** [comment]
Working on automating this now, basically you need (in format command: package):

#qrencode: qrencode
#base64: coreutils
#zbarimg: install zbar-tools
#gzip: gzip
#gunzip: gzip
#split: coreutils
#dd: coreutils
#truncate: coreutils
#convert: imagemagick
#img2pdf: img2pdf
#zbar-tools: zbar-tools

Installing these on Ubuntu18.04LTS should give you high enough versions for full functionability. Checking for package versions etc is on my todo list, will do ASAP.

Let me know if installing all packages fixes your problem @gtheler :) .

**Comment by gtheler** [comment]
Try
```
for i in qrencode base64 zbarimg gzip gunzip split dd truncate convert img2pdf zbar-tools; do
 if [ -z "`which $i`" ]; then
   echo "error: $i is not installed"
   exit 1
 fi
done
```

**Comment by jerabaul29** [comment]
Yes, working on it, for now going to eat, will fix this tonight :)

**Comment by jerabaul29** [comment]
@gtheler thanks for your help, now integrated in the package:

https://github.com/jerabaul29/qrdump/blob/39b95b35832df7d0295163721daaf2c834195493/src/qrdump.sh#L8-L12

https://github.com/jerabaul29/qrdump/blob/39b95b35832df7d0295163721daaf2c834195493/src/check_dependencies.sh#L1-L8

I went quickly through the code and checked, that should be all that is needed. But curious to hear if this helps fix the no pdf output problem. Let me know if this is not enough. If this is enough, can you confirm and close? :)

**Comment by jerabaul29** [comment]
Is this still a problem @gtheler or did the warnings about missing packages allowed you to catch all missing dependencies and get a pdf out? :)

**Comment by gtheler** [comment]
well I installed img2pdf and it worked so I think this can be closed

**Comment by jerabaul29** [comment]
That's great, thanks, closing.
